/*
 * Api napisan u swageru
 *
 * Kalkulator api za računanje cijene struje
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Koeficijenti :  IEquatable<Koeficijenti>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Koeficijenti" /> class.
        /// </summary>
        /// <param name="JeftiniKoeficijent">JeftiniKoeficijent.</param>
        /// <param name="SkupiKoeficijent">SkupiKoeficijent.</param>
        public Koeficijenti(double? JeftiniKoeficijent = null, double? SkupiKoeficijent = null)
        {
            this.JeftiniKoeficijent = JeftiniKoeficijent;
            this.SkupiKoeficijent = SkupiKoeficijent;
            
        }

        public int ID { get; set; }

        /// <summary>
        /// Gets or Sets JeftiniKoeficijent
        /// </summary>
        [DataMember(Name="JeftiniKoeficijent")]
        public double? JeftiniKoeficijent { get; set; }

        /// <summary>
        /// Gets or Sets SkupiKoeficijent
        /// </summary>
        [DataMember(Name="SkupiKoeficijent")]
        public double? SkupiKoeficijent { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Koeficijenti {\n");
            sb.Append("  JeftiniKoeficijent: ").Append(JeftiniKoeficijent).Append("\n");
            sb.Append("  SkupiKoeficijent: ").Append(SkupiKoeficijent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Koeficijenti)obj);
        }

        /// <summary>
        /// Returns true if Koeficijenti instances are equal
        /// </summary>
        /// <param name="other">Instance of Koeficijenti to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Koeficijenti other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.JeftiniKoeficijent == other.JeftiniKoeficijent ||
                    this.JeftiniKoeficijent != null &&
                    this.JeftiniKoeficijent.Equals(other.JeftiniKoeficijent)
                ) && 
                (
                    this.SkupiKoeficijent == other.SkupiKoeficijent ||
                    this.SkupiKoeficijent != null &&
                    this.SkupiKoeficijent.Equals(other.SkupiKoeficijent)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.JeftiniKoeficijent != null)
                    hash = hash * 59 + this.JeftiniKoeficijent.GetHashCode();
                    if (this.SkupiKoeficijent != null)
                    hash = hash * 59 + this.SkupiKoeficijent.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Koeficijenti left, Koeficijenti right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Koeficijenti left, Koeficijenti right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
